version: '3.6'
services:
  golang-dragonflydb-example:
    hostname: golang-dragonflydb-example
    # TODO: Build
    ports:
      - "8000:8000"
      - "8080:8080"
    depends_on:
      - redis
    #env_file:
    #  - production.sample.env
  dragonflydb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    hostname: dragonflydb
    ports:
      - "6379:6379"
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
